version: '3.7'
services:
   db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: facturacion
      MYSQL_ROOT_PASSWORD: colombia123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'app'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  
  